# Run unit tests on any branch/fork pull request
on:
  pull_request

name: Unit tests

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:

    - run: echo $MY
      env: 
        MY: ${{ secrets.MY }}
    - run: echo "Unit tests... success! ;-)"